title: Matias Szarfer
email: matias@szarfer.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Software Engineer who works as a freelancer. I can make different kinds of websites, apps or servers.

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
